// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDHIzlVbH_InUf64XFY0hInYlUBIrd8s',
    appId: '1:445894203200:android:443961c8ebc5627a2d0ca5',
    messagingSenderId: '445894203200',
    projectId: 'blackjack21-v2',
    storageBucket: 'blackjack21-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlDa8aTtS5BBIe-4PQSCsTg59PcHQwG0',
    appId: '1:445894203200:ios:1ad783b723c1e8602d0ca5',
    messagingSenderId: '445894203200',
    projectId: 'blackjack21-v2',
    storageBucket: 'blackjack21-v2.firebasestorage.app',
    androidClientId: '445894203200-od9us9ivqslgc4d6geeh4lgon19ccu8t.apps.googleusercontent.com',
    iosClientId: '445894203200-jtjnu5ih0uommsfd3ru507mridgnki23.apps.googleusercontent.com',
    iosBundleId: 'com.micorlov.blackjack21V2',
  );
}
